
export CONFIG_SERVICE_PASSWORD=mypassword 
export MONGODB_PASSWORD=mypassword 
export ACCOUNT_SERVICE_PASSWORD=mypassword 
export STATISTICS_SERVICE_PASSWORD=mypassword 
export NOTIFICATION_SERVICE_PASSWORD=mypassword 
