server:
  port: 8888
  
management:
  context_path: /admin
  
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    
spring:
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/develop4/cloud-config-files
          uri: https://github.com/spring-cloud-samples/config-repo
          
          
security:
  user:
    password: ${CONFIG_SERVICE_PASSWORD:mypassword}