spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native    
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/develop4/cloud-config-files
#          uri: https://github.com/spring-cloud-samples/config-repo
      
server:
  port: 8888
      
security:
  user:
    password: ${CONFIG_SERVICE_PASSWORD:mypassword}