spring:
  cloud:
    config:
      server:
#        native:
#          search-locations: classpath:/shared-local
        git:
          uri: https://github.com/develop4/cloud-config-files/example
  profiles:
     active: native

server:
  port: 8888

security:
  user:
    password: ${CONFIG_SERVICE_PASSWORD:mypassword}